valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/guitar-delay-c-1iter-0.0-0.96.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/guitar.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/guitar-delay-c-1iter-0.0-0.96.wav 1 -d 0.0 0.96
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/guitar-delay-asm-1iter-0.0-0.96.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/guitar.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/guitar-delay-asm-1iter-0.0-0.96.wav 1 -D 0.0 0.96
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/gibson-delay-c-1iter-4.0-0.71.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/gibson.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/gibson-delay-c-1iter-4.0-0.71.wav 1 -d 4.0 0.71
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/gibson-delay-asm-1iter-4.0-0.71.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/gibson.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/gibson-delay-asm-1iter-4.0-0.71.wav 1 -D 4.0 0.71
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/beirut-delay-c-1iter-3.2-0.78.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/beirut.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/beirut-delay-c-1iter-3.2-0.78.wav 1 -d 3.2 0.78
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/beirut-delay-asm-1iter-3.2-0.78.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/beirut.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/beirut-delay-asm-1iter-3.2-0.78.wav 1 -D 3.2 0.78
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/DiMarzio-delay-c-1iter-3.3-0.72.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/DiMarzio.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/DiMarzio-delay-c-1iter-3.3-0.72.wav 1 -d 3.3 0.72
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/DiMarzio-delay-asm-1iter-3.3-0.72.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/DiMarzio.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/DiMarzio-delay-asm-1iter-3.3-0.72.wav 1 -D 3.3 0.72
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/guitar-flanger-c-1iter-0.006-0.58-0.74.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/guitar.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/guitar-flanger-c-1iter-0.006-0.58-0.74.wav 1 -f 0.006 0.58 0.74
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/guitar-flanger-asm-1iter-0.006-0.58-0.74.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/guitar.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/guitar-flanger-asm-1iter-0.006-0.58-0.74.wav 1 -F 0.006 0.58 0.74
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/gibson-flanger-c-1iter-0.007-0.8-0.7.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/gibson.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/gibson-flanger-c-1iter-0.007-0.8-0.7.wav 1 -f 0.007 0.8 0.7
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/gibson-flanger-asm-1iter-0.007-0.8-0.7.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/gibson.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/gibson-flanger-asm-1iter-0.007-0.8-0.7.wav 1 -F 0.007 0.8 0.7
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/beirut-flanger-c-1iter-0.012-0.51-0.71.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/beirut.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/beirut-flanger-c-1iter-0.012-0.51-0.71.wav 1 -f 0.012 0.51 0.71
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/beirut-flanger-asm-1iter-0.012-0.51-0.71.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/beirut.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/beirut-flanger-asm-1iter-0.012-0.51-0.71.wav 1 -F 0.012 0.51 0.71
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/DiMarzio-flanger-c-1iter-0.007-0.67-0.68.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/DiMarzio.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/DiMarzio-flanger-c-1iter-0.007-0.67-0.68.wav 1 -f 0.007 0.67 0.68
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/DiMarzio-flanger-asm-1iter-0.007-0.67-0.68.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/DiMarzio.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/DiMarzio-flanger-asm-1iter-0.007-0.67-0.68.wav 1 -F 0.007 0.67 0.68
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/guitar-vibrato-c-1iter-0.0-1.85.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/guitar.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/guitar-vibrato-c-1iter-0.0-1.85.wav 1 -v 0.0 1.85
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/guitar-vibrato-asm-1iter-0.0-1.85.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/guitar.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/guitar-vibrato-asm-1iter-0.0-1.85.wav 1 -V 0.0 1.85
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/gibson-vibrato-c-1iter-0.003-3.11.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/gibson.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/gibson-vibrato-c-1iter-0.003-3.11.wav 1 -v 0.003 3.11
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/gibson-vibrato-asm-1iter-0.003-3.11.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/gibson.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/gibson-vibrato-asm-1iter-0.003-3.11.wav 1 -V 0.003 3.11
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/beirut-vibrato-c-1iter-0.0-0.32.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/beirut.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/beirut-vibrato-c-1iter-0.0-0.32.wav 1 -v 0.0 0.32
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/beirut-vibrato-asm-1iter-0.0-0.32.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/beirut.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/beirut-vibrato-asm-1iter-0.0-0.32.wav 1 -V 0.0 0.32
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/DiMarzio-vibrato-c-1iter-0.0-4.91.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/DiMarzio.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/DiMarzio-vibrato-c-1iter-0.0-4.91.wav 1 -v 0.0 4.91
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/DiMarzio-vibrato-asm-1iter-0.0-4.91.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/DiMarzio.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/DiMarzio-vibrato-asm-1iter-0.0-4.91.wav 1 -V 0.0 4.91
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/guitar-bitcrusher-c-1iter-7-2693.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/guitar.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/guitar-bitcrusher-c-1iter-7-2693.wav 1 -b 7 2693
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/guitar-bitcrusher-asm-1iter-7-2693.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/guitar.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/guitar-bitcrusher-asm-1iter-7-2693.wav 1 -B 7 2693
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/gibson-bitcrusher-c-1iter-15-8233.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/gibson.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/gibson-bitcrusher-c-1iter-15-8233.wav 1 -b 15 8233
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/gibson-bitcrusher-asm-1iter-15-8233.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/gibson.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/gibson-bitcrusher-asm-1iter-15-8233.wav 1 -B 15 8233
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/beirut-bitcrusher-c-1iter-15-6632.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/beirut.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/beirut-bitcrusher-c-1iter-15-6632.wav 1 -b 15 6632
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/beirut-bitcrusher-asm-1iter-15-6632.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/beirut.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/beirut-bitcrusher-asm-1iter-15-6632.wav 1 -B 15 6632
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/DiMarzio-bitcrusher-c-1iter-16-2617.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/DiMarzio.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/DiMarzio-bitcrusher-c-1iter-16-2617.wav 1 -b 16 2617
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/DiMarzio-bitcrusher-asm-1iter-16-2617.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/DiMarzio.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/DiMarzio-bitcrusher-asm-1iter-16-2617.wav 1 -B 16 2617
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/guitar-wahwah-c-1iter-0.03-585-3248-1127.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/guitar.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/guitar-wahwah-c-1iter-0.03-585-3248-1127.wav 1 -w 0.03 585 3248 1127
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/guitar-wahwah-asm-1iter-0.03-585-3248-1127.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/guitar.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/guitar-wahwah-asm-1iter-0.03-585-3248-1127.wav 1 -W 0.03 585 3248 1127
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/gibson-wahwah-c-1iter-0.06-837-3055-2909.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/gibson.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/gibson-wahwah-c-1iter-0.06-837-3055-2909.wav 1 -w 0.06 837 3055 2909
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/gibson-wahwah-asm-1iter-0.06-837-3055-2909.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/gibson.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/gibson-wahwah-asm-1iter-0.06-837-3055-2909.wav 1 -W 0.06 837 3055 2909
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/beirut-wahwah-c-1iter-0.04-719-3041-2472.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/beirut.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/beirut-wahwah-c-1iter-0.04-719-3041-2472.wav 1 -w 0.04 719 3041 2472
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/beirut-wahwah-asm-1iter-0.04-719-3041-2472.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/beirut.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/beirut-wahwah-asm-1iter-0.04-719-3041-2472.wav 1 -W 0.04 719 3041 2472
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/DiMarzio-wahwah-c-1iter-0.01-859-2541-2322.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/DiMarzio.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/DiMarzio-wahwah-c-1iter-0.01-859-2541-2322.wav 1 -w 0.01 859 2541 2322
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/DiMarzio-wahwah-asm-1iter-0.01-859-2541-2322.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/DiMarzio.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/DiMarzio-wahwah-asm-1iter-0.01-859-2541-2322.wav 1 -W 0.01 859 2541 2322
