valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/guitar-delay-c-1iter-4.5-0.92.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/guitar.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/guitar-delay-c-1iter-4.5-0.92.wav 1 -d 4.5 0.92
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/guitar-delay-asm-1iter-4.5-0.92.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/guitar.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/guitar-delay-asm-1iter-4.5-0.92.wav 1 -D 4.5 0.92
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/gibson-delay-c-1iter-2.0-0.73.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/gibson.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/gibson-delay-c-1iter-2.0-0.73.wav 1 -d 2.0 0.73
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/gibson-delay-asm-1iter-2.0-0.73.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/gibson.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/gibson-delay-asm-1iter-2.0-0.73.wav 1 -D 2.0 0.73
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/beirut-delay-c-1iter-3.6-0.83.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/beirut.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/beirut-delay-c-1iter-3.6-0.83.wav 1 -d 3.6 0.83
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/beirut-delay-asm-1iter-3.6-0.83.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/beirut.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/beirut-delay-asm-1iter-3.6-0.83.wav 1 -D 3.6 0.83
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/DiMarzio-delay-c-1iter-1.1-0.97.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/DiMarzio.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/DiMarzio-delay-c-1iter-1.1-0.97.wav 1 -d 1.1 0.97
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/DiMarzio-delay-asm-1iter-1.1-0.97.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/DiMarzio.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/DiMarzio-delay-asm-1iter-1.1-0.97.wav 1 -D 1.1 0.97
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/guitar-flanger-c-1iter-0.006-0.9-0.66.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/guitar.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/guitar-flanger-c-1iter-0.006-0.9-0.66.wav 1 -f 0.006 0.9 0.66
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/guitar-flanger-asm-1iter-0.006-0.9-0.66.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/guitar.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/guitar-flanger-asm-1iter-0.006-0.9-0.66.wav 1 -F 0.006 0.9 0.66
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/gibson-flanger-c-1iter-0.014-0.62-0.66.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/gibson.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/gibson-flanger-c-1iter-0.014-0.62-0.66.wav 1 -f 0.014 0.62 0.66
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/gibson-flanger-asm-1iter-0.014-0.62-0.66.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/gibson.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/gibson-flanger-asm-1iter-0.014-0.62-0.66.wav 1 -F 0.014 0.62 0.66
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/beirut-flanger-c-1iter-0.012-0.37-0.68.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/beirut.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/beirut-flanger-c-1iter-0.012-0.37-0.68.wav 1 -f 0.012 0.37 0.68
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/beirut-flanger-asm-1iter-0.012-0.37-0.68.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/beirut.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/beirut-flanger-asm-1iter-0.012-0.37-0.68.wav 1 -F 0.012 0.37 0.68
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/DiMarzio-flanger-c-1iter-0.013-0.37-0.7.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/DiMarzio.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/DiMarzio-flanger-c-1iter-0.013-0.37-0.7.wav 1 -f 0.013 0.37 0.7
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/DiMarzio-flanger-asm-1iter-0.013-0.37-0.7.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/DiMarzio.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/DiMarzio-flanger-asm-1iter-0.013-0.37-0.7.wav 1 -F 0.013 0.37 0.7
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/guitar-vibrato-c-1iter-0.0-0.95.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/guitar.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/guitar-vibrato-c-1iter-0.0-0.95.wav 1 -v 0.0 0.95
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/guitar-vibrato-asm-1iter-0.0-0.95.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/guitar.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/guitar-vibrato-asm-1iter-0.0-0.95.wav 1 -V 0.0 0.95
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/gibson-vibrato-c-1iter-0.002-1.65.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/gibson.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/gibson-vibrato-c-1iter-0.002-1.65.wav 1 -v 0.002 1.65
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/gibson-vibrato-asm-1iter-0.002-1.65.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/gibson.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/gibson-vibrato-asm-1iter-0.002-1.65.wav 1 -V 0.002 1.65
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/beirut-vibrato-c-1iter-0.002-3.03.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/beirut.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/beirut-vibrato-c-1iter-0.002-3.03.wav 1 -v 0.002 3.03
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/beirut-vibrato-asm-1iter-0.002-3.03.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/beirut.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/beirut-vibrato-asm-1iter-0.002-3.03.wav 1 -V 0.002 3.03
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/DiMarzio-vibrato-c-1iter-0.003-4.96.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/DiMarzio.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/DiMarzio-vibrato-c-1iter-0.003-4.96.wav 1 -v 0.003 4.96
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/DiMarzio-vibrato-asm-1iter-0.003-4.96.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/DiMarzio.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/DiMarzio-vibrato-asm-1iter-0.003-4.96.wav 1 -V 0.003 4.96
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/guitar-bitcrusher-c-1iter-7-7222.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/guitar.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/guitar-bitcrusher-c-1iter-7-7222.wav 1 -b 7 7222
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/guitar-bitcrusher-asm-1iter-7-7222.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/guitar.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/guitar-bitcrusher-asm-1iter-7-7222.wav 1 -B 7 7222
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/gibson-bitcrusher-c-1iter-13-6007.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/gibson.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/gibson-bitcrusher-c-1iter-13-6007.wav 1 -b 13 6007
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/gibson-bitcrusher-asm-1iter-13-6007.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/gibson.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/gibson-bitcrusher-asm-1iter-13-6007.wav 1 -B 13 6007
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/beirut-bitcrusher-c-1iter-15-6368.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/beirut.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/beirut-bitcrusher-c-1iter-15-6368.wav 1 -b 15 6368
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/beirut-bitcrusher-asm-1iter-15-6368.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/beirut.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/beirut-bitcrusher-asm-1iter-15-6368.wav 1 -B 15 6368
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/DiMarzio-bitcrusher-c-1iter-12-9708.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/DiMarzio.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/DiMarzio-bitcrusher-c-1iter-12-9708.wav 1 -b 12 9708
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/DiMarzio-bitcrusher-asm-1iter-12-9708.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/DiMarzio.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/DiMarzio-bitcrusher-asm-1iter-12-9708.wav 1 -B 12 9708
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/guitar-wahwah-c-1iter-0.05-429-3332-2181.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/guitar.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/guitar-wahwah-c-1iter-0.05-429-3332-2181.wav 1 -w 0.05 429 3332 2181
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/guitar-wahwah-asm-1iter-0.05-429-3332-2181.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/guitar.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/guitar-wahwah-asm-1iter-0.05-429-3332-2181.wav 1 -W 0.05 429 3332 2181
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/gibson-wahwah-c-1iter-0.09-602-3210-1466.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/gibson.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/gibson-wahwah-c-1iter-0.09-602-3210-1466.wav 1 -w 0.09 602 3210 1466
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/gibson-wahwah-asm-1iter-0.09-602-3210-1466.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/gibson.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/gibson-wahwah-asm-1iter-0.09-602-3210-1466.wav 1 -W 0.09 602 3210 1466
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/beirut-wahwah-c-1iter-0.09-965-2808-2743.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/beirut.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/beirut-wahwah-c-1iter-0.09-965-2808-2743.wav 1 -w 0.09 965 2808 2743
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/beirut-wahwah-asm-1iter-0.09-965-2808-2743.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/beirut.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/beirut-wahwah-asm-1iter-0.09-965-2808-2743.wav 1 -W 0.09 965 2808 2743
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/DiMarzio-wahwah-c-1iter-0.04-479-3153-2512.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/DiMarzio.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/DiMarzio-wahwah-c-1iter-0.04-479-3153-2512.wav 1 -w 0.04 479 3153 2512
valgrind --tool=callgrind --callgrind-out-file=/home/petemir/Projects/orga2dantooine/pedalerIA64/src/callgrind/DiMarzio-wahwah-asm-1iter-0.04-479-3153-2512.wav.out --dump-instr=yes --collect-jumps=yes /home/petemir/Projects/orga2dantooine/pedalerIA64/src/main /home/petemir/Projects/orga2dantooine/pedalerIA64/src/inputExamples/DiMarzio.wav /home/petemir/Projects/orga2dantooine/pedalerIA64/src/output/DiMarzio-wahwah-asm-1iter-0.04-479-3153-2512.wav 1 -W 0.04 479 3153 2512
